### ISSUE TITLE
Game Breaking Glitch For Cars

### ISSUE THREAD

**Issue by Crazy-tech458** [KaleenBhaiya00/kbfw-fakeplates#1]
Hi, I'm a developer on a server, we recently installed your script and while it is working well it is causing a game-breaking glitch. When u steal a plate off someone's car and install it on your own car the issue is that it won't register that the car is yours anymore and tells you that the keys for your car are gone.

**Comment by KaleenBhaiya00** [comment]
its reset after stored bro

**Comment by Crazy-tech458** [comment]
Okay thank you for letting me know if this continues happening i will let you know and do a new Issue with screenshots as well
